apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:587'
      smtp_from: '793416688@qq.com'
      smtp_auth_username: '793416688@qq.com'
      smtp_auth_password: 'cyhcbkdussrmbebc'

    route:
      receiver: 'email'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      #routes:
      #- receiver: 'dingtalk'
      #- receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: '87740965@qq.com'
        send_resolved: true
    #- name: 'dingtalk'
      #webhook_configs:
        #- url: http://dingtalk:8060/dingtalk/webhook/send
          #send_resolved: true

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
