apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    k8s-app: alertmanager
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: 9093
    nodePort: 30903
  selector:
    k8s-app: alertmanager
