# http-grafana
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.dongye.com`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
    middlewares:
    - name: auto-https


# https-grafana
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.dongye.com`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
  tls:
    secretName: dongye-tls   # 注意namespaces

