apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      scrape_timeout:      10s
      external_labels:
        cluster: "kubernetes"

    #alerting:
      #alertmanagers:
      #- static_configs:
        #- targets: ['alertmanager:9093']

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.

    rule_files:
      - "/etc/prometheus/alert.rules"
      #- "second_rules.yml"

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: prometheus

    - job_name: 'k8s-node'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
        action: replace
      - source_labels: [__meta_kubernetes_node_name]
        action: replace
        target_label: node
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__meta_kubernetes_node_address_InternalIP]
        action: replace
        target_label: ip

    #- job_name: 'nacos'
    #  metrics_path: '/nacos/actuator/prometheus'
      # scheme defaults to 'http'.
    #  static_configs:
    #  - targets: ['172.17.67.190:8848']

    #- job_name: 'host_list'
      #file_sd_configs:
      #- refresh_interval: 1m # 设置每分钟重新读取一次文件内容,默认5m
        #files:
        #- "/etc/prometheus/targets.json"

  alert.rules: |
    groups:
    - name: hostStatsAlert
      rules:
      - alert: '主机CPU使用率'
        expr: sum(avg without (cpu)(irate(node_cpu_seconds_total{mode!='idle'}[5m]))) by (instance) > 0.90
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "实例 {{ $labels.instance }} CPU 使用率过高"
          description: "{{ $labels.instance }} CPU 使用率超过 90% (当前值: {{ $value }})"
      - alert: '主机内存使用率'
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.90
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "实例 {{ $labels.instance }} 内存使用过高"
          description: "{{ $labels.instance }} 内存使用率超过 90% (当前值: {{ $value }})"  
