apiVersion: v1
kind: Secret
metadata:
  name: my-aliyun
  namespace: public-service
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJtaW9zeTE5OTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiJGZHkuMTk5NiIsImF1dGgiOiJiV2x2YzNreE9UazJRR2R0WVdsc0xtTnZiVHBHWkhrdU1UazVOZz09In19fQ==
type: kubernetes.io/dockerconfigjson
