# nexus service
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: public-service
  labels:
    app: nexus
spec:
  type: NodePort
#  clusterIP: None
  ports:
    - name: web
      nodePort: 30111
      port: 8081
      targetPort: 8081
  selector:
    app: nexus


# nginx 代理服务
---
apiVersion: v1
kind: Service
metadata:
  name: docker-proxy
  namespace: public-service
  labels:
    app: nexus
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  clusterIP: None
  selector:
    app: nexus

