---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: public-service
spec:
  serviceName: nexus
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.30.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8081
        # - name: docker-private
        #   containerPort: 8082
        # - name: docker-public
        #   containerPort: 8083

        livenessProbe:          #存活探针
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
        readinessProbe:         #就绪探针
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
        env:
        - name: INSTALL4J_ADD_VM_PARAMS  #设置分配资源大小，一定要等于或小于resources设置的值
          value: "
                  -Xms1200M
                  -Xmx1200M
                  -XX:MaxDirectMemorySize=2G
                  -XX:+UnlockExperimentalVMOptions
                  -XX:+UseCGroupMemoryLimitForHeap
                 "
        resources:      #资源限制
          limits:
            cpu: 1000m  #推荐设置为4000m以上cpu，由于资源有限，所以都是设置的最小值
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi

        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data

      - name: nginx-proxy
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80

        - name: https
          containerPort: 443

        volumeMounts:
        - name: docker-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf

        - name: dongye-tls
          mountPath: "/etc/nginx/certs"
          readOnly: true          

      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-nfs     #设置为上面创建的 PVC

      - name: docker-config
        configMap:
          name: docker-config

      - name: dongye-tls
        secret:
          secretName: dongye-tls
          items: 
            - key: tls.crt
              path: tls.crt

            - key: tls.key
              path: tls.key
