apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: public-service
data:
  nginx.conf: |
    upstream nexus_docker_get {
        # docker-public
        server 127.0.0.1:8083;
    }

    upstream nexus_docker_put {
        # docker-private
        server 127.0.0.1:8082;
    }
    server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/tls.crt; # 证书路径根据上面生成的来定
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;        

        client_max_body_size 0;
        # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;
        # 设置默认使用推送代理
        set $upstream "nexus_docker_put";
        # 当请求是GET，也就是拉取镜像的时候，这里改为拉取代理，如此便解决了拉取和推送的端口统一
        if ( $request_method ~* 'GET') {
            set $upstream "nexus_docker_get";
        }
        # 只有本地仓库才支持搜索，所以将搜索请求转发到本地仓库，否则出现500报错
        if ($request_uri ~ '/search') {
            set $upstream "nexus_docker_put";
        }
        index index.html index.htm index.php;
        location / {
            proxy_pass http://$upstream;
            proxy_connect_timeout 3600;
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_buffering off;
            proxy_request_buffering off;
            # 修复nginx位于ingress之后导致镜像推送上传失败问题https://docs.docker.com/registry/recipes/nginx/
            # 位于ingress后需要注释下面配置
            #proxy_set_header Host $host:$server_port;
            #proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #proxy_set_header X-Forwarded-Proto "http";
        }
    }

