---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9100
    targetPort: 9100
    protocol: TCP
  type: ClusterIP
  selector:
    app: node-exporter
