---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  ports:
    - name: web
      port: 80
      nodePort: 30080
    - name: websecure
      port: 443
      nodePort: 30443
  type: NodePort
  selector:
    app: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ui
  namespace: kube-system
  labels:
    app: traefik-ui
spec:
  ports:
    - name: admin
      port: 8080
  selector:
    app: traefik
