apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: 33000
  selector:
    app: grafana
