apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: public-service
data:
  SERVICE_NAME: "nacos-headless"
  DOMAIN_NAME: "cluster.local"
  NACOS_REPLICAS: "3"
  PREFER_HOST_MODE: "hostname"
  NACOS_SERVER_PORT: "8848"
  NACOS_APPLICATION_PORT: "8848"
  JVM_XMX: "2g"
  JVM_XMS: "2g"
  JVM_XMN: "1g"
  MYSQL_SERVICE_HOST: "10.193.149.201"
  MYSQL_SERVICE_DB_NAME: "nacos"
  MYSQL_SERVICE_PORT: "30046"
  MYSQL_SERVICE_USER: "nacos"
  MYSQL_SERVICE_PASSWORD: "v9KSLfJFOd_eF"

